return {
	{name="shop1", service=1 ,sales=2 ,popular=3},
	{name="shop2", service=10 ,sales=5 ,popular=10},
	{name="shop3", service=3 ,sales=8 ,popular=2},
	{name="shop4", service=5 ,sales=5 ,popular=5},
	{name="shop5", service=4 ,sales=3 ,popular=4},
	{name="shop6", service=7 ,sales=4 ,popular=6},
	{name="shop7", service=5 ,sales=6 ,popular=7},
	{name="shop8", service=1 ,sales=8 ,popular=2},
	{name="shop9", service=3 ,sales=7 ,popular=8},
	{name="shop10", service=2 ,sales=8 ,popular=1},
	{name="shop11", service=4 ,sales=10 ,popular=6},
	{name="shop12", service=7 ,sales=2 ,popular=3},
	{name="shop13", service=6 ,sales=3 ,popular=4},
	{name="shop14", service=8 ,sales=1 ,popular=2},
	{name="shop15", service=9 ,sales=5 ,popular=4},
	{name="shop16", service=5 ,sales=8 ,popular=2},
	{name="shop17", service=0 ,sales=5 ,popular=1},
	{name="shop18", service=2 ,sales=8 ,popular=3},
	{name="shop19", service=3 ,sales=8 ,popular=2},
	}