return {
	{name="Trelawney", service=3 ,power=3 ,speed=8 ,dex=7 ,magic=1 ,spirit=4 ,stamnina=9},
	{name="Simons", service=1 ,power=5 ,speed=8 ,dex=8 ,magic=0 ,spirit=9 ,stamnina=9},
	{name="Bulman", service=0 ,power=2 ,speed=4 ,dex=4 ,magic=2 ,spirit=4 ,stamnina=4},
	{name="Bennet", service=8 ,power=5 ,speed=7 ,dex=5 ,magic=3 ,spirit=0 ,stamnina=8},
	{name="Karkaroff", service=1 ,power=7 ,speed=3 ,dex=9 ,magic=1 ,spirit=0 ,stamnina=4},
	{name="Flanagan", service=1 ,power=5 ,speed=4 ,dex=0 ,magic=4 ,spirit=3 ,stamnina=7},
	{name="Lum", service=1 ,power=8 ,speed=6 ,dex=5 ,magic=5 ,spirit=4 ,stamnina=6},
	{name="Vachell", service=6 ,power=4 ,speed=8 ,dex=8 ,magic=7 ,spirit=4 ,stamnina=3},
	{name="Overstreet", service=7 ,power=4 ,speed=7 ,dex=6 ,magic=3 ,spirit=9 ,stamnina=6},
	{name="Angyal", service=6 ,power=4 ,speed=1 ,dex=3 ,magic=8 ,spirit=1 ,stamnina=3},
	{name="Whiting", service=0 ,power=9 ,speed=7 ,dex=0 ,magic=6 ,spirit=0 ,stamnina=8},
	{name="Goodson", service=2 ,power=2 ,speed=7 ,dex=4 ,magic=7 ,spirit=7 ,stamnina=0},
	{name="Bankes", service=9 ,power=7 ,speed=3 ,dex=0 ,magic=4 ,spirit=3 ,stamnina=3},
	{name="Esmond", service=2 ,power=5 ,speed=2 ,dex=6 ,magic=5 ,spirit=7 ,stamnina=1},
	{name="Rodgers", service=3 ,power=2 ,speed=2 ,dex=1 ,magic=5 ,spirit=1 ,stamnina=5},
	{name="Eggleston", service=8 ,power=4 ,speed=1 ,dex=2 ,magic=5 ,spirit=5 ,stamnina=2},
	{name="Gwatkin", service=1 ,power=4 ,speed=7 ,dex=7 ,magic=3 ,spirit=8 ,stamnina=2},
	{name="Baily", service=7 ,power=1 ,speed=8 ,dex=6 ,magic=2 ,spirit=9 ,stamnina=2},
	{name="Flanders", service=0 ,power=9 ,speed=4 ,dex=9 ,magic=6 ,spirit=9 ,stamnina=3},
}